### ISSUE TITLE
Change `lua/jj` to `lua/telescope-jj`

### ISSUE THREAD

**Issue by Cretezy** [zschreur/telescope-jj.nvim#6]
Having the code at `lua/jj` makes this package use `require("jj")`. It should be `lua/telescope-jj` for `require("telescope-jj")` to not interfere with any future `jj` plugin.

**Comment by zschreur** [comment]
Makes sense - I’m out of town for the next week so I’ll take a closer look when I am back. Thanks for the help I appreciate it!

**Comment by Cretezy** [comment]
I've opened a PR to do this change: https://github.com/zschreur/telescope-jj.nvim/pull/7
